### ISSUE TITLE
What is the fastest way to start an emulator in Travis?

### ISSUE THREAD

**Issue by mmcc007** [thyrlian/AndroidSDK#18]
I've been able to get an emulator to start on a macOS in Docker following your instructions... awesome!

However, when ever I start an emulator in Travis (using my own method), it takes almost 5 minutes (on an older ARM emulator).
https://travis-ci.org/brianegan/flutter_architecture_samples/jobs/502926447#L1186

Do you have any suggestions on how I can get an emulator to start faster on Travis? 

Should I try running the emulator in docker (doesn't seem like there is any advantage in doing that)?

Or, should I try starting a more recent emulator (which one)?

Or is there an alternative way? 

As far as alternatives:
1. Using an emulator default snapshot .
Seems like it should be possible. The problem is in finding the best way to download the snapshot image (~10GB). Maybe use AWS S3? Or possibly bundle the snapshot image into a docker image and start the emulator in the docker container?
1. Using a Docker checkpoint . 
    ```
    docker checkpoint create <container name> <checkpointname>
    docker start –checkpoint <checkpointname> <container name>
    ```
    Still have to find a way to download the checkpoint image to travis (S3?)
    (So far, I have not been able to get this feature to work on my local machine (macOS).)
1. Maintain a running emulator on a server . 
Then connect to it from travis via ssh. Problem is, since travis runs jobs in parallel, would have to maintain multiple emulators and find a way to locate available emulator.
1. Some other way??

(BTW: I tried connecting to Genymotion and it worked. But don't want to pay the price.)

**Comment by thyrlian** [comment]
Hi @mmcc007, thanks for using this Docker image, and I'm glad that it works for you.

First, I'd like to understand your issue from several perspectives, please correct me if I'm wrong:

**Problem**:
Running integration tests with ARM emulator on Travis CI is slow.  It took about 16 mins to run with your given [build job](https://travis-ci.org/brianegan/flutter_architecture_samples/jobs/502926447).

**Situation**:
* It's a [open source project](https://github.com/brianegan/flutter_architecture_samples).
* It's built with Flutter, meaning the CI has to support iOS build as well, apart from Android.
* Doesn't want to use any paid plan.

**Goal**:
To make integration tests running faster.

**Comment by thyrlian** [comment]
**Q**: Should I try running the emulator in docker (doesn't seem like there is any advantage in doing that)?
**A**: As you've answered by yourself, no need to do so as no benefit.

**Q**: Should I try starting a more recent emulator (which one)?
**A**: it won't make any perceptible difference.

Speaking of alternative ways:

**Q**: Using an emulator default snapshot.
**A**: Yes, snapshot will reduce the boot time, and would also help doing some OS-level pre-configuration.  But indeed the serving of snapshot is a question, and should be a separate job from the project's CI job.

**Q**: Using a Docker checkpoint.
**A**: It's good too.  Travis CI allows you to install newer Docker version on your own, so that you can get the one which supports checkpoint API ([>= v1.25](https://docs.docker.com/engine/reference/commandline/checkpoint/)).  Here comes the questions.  Where to save the checkpoint?  Travis CI doesn't persist that.  Even if yes, you have to maintain two images - one for normal Android build job (due to the change is likely to be more frequent, though you could mount the Android SDK, but you can't do that on Travis, as you need a place to persist the SDK), and another one for Android emulator (where you should create checkpoint to save the memory state).  To be honest, I have never tried it, just believe it should work.

**Q**: Maintain a running emulator on a server.
**A**: As you said, maintaining, and load balancing requires a lot of work.

**Q**: Some other way??
**A**:
* Genymotion (unfortunately it's not free)
* X86 emulator (faster in boot and execution, but requires KVM, which means your cloud provider should support nested virtualization)
  * Microsoft Azure
  * [AWS EC2 Bare Metal Instance](https://aws.amazon.com/blogs/compute/running-hyper-v-on-amazon-ec2-bare-metal-instances/), it's fairly pricy
  * Travis CI, current status is still [no](https://github.com/travis-ci/travis-ci/issues/1419)
  * [Firebase Test Lab](https://firebase.google.com/docs/test-lab/), unfortunately not free either

There is no perfect free and fast solution.  Having said that, still you can try other free solution which may bring you some performance improvement.

For instance, here is an [open source Android project](https://github.com/thyrlian/AwesomeValidation) of mine.  I've configured two CI build jobs using two CI providers - Travis CI and CircleCI.  Below is a simple comparison for your information.

[Travis CI](https://travis-ci.org/thyrlian/AwesomeValidation/builds) - averagely over **15 mins** per build
[CircleCI](https://circleci.com/gh/thyrlian/AwesomeValidation/tree/master) - averagely **8 mins** per build

Maybe you could give CircleCI a try?  It supports iOS build as well.

Hope you're satisfied with my answer.

**Comment by thyrlian** [comment]
BTW, since your project is built with Flutter, maybe you wanna try [enabling Skia rendering for Android UI](https://developer.android.com/studio/run/emulator-acceleration#skia-emulator)

**Comment by thyrlian** [comment]
@mmcc007  any comments from your side?  Otherwise I'd like to close this issue, thanks.

**Comment by mmcc007** [comment]
I've been doing some experimentation based on your detailed response. (there are many great options to try).

I wanted to respond with some evidence-based results.  (not there yet)

I am using docker on a remote linux VM (ran into port problems on local macOS) to do some repeatable testing before uploading some kind of working example of use case to travis. 

So far I can get a flutter test to run (from container, not host) on one emulator, but not on other emulators.

Ran into problem with exposing adb port forwarding from container when running flutter test on host (may not need to solve this problem when running on travis). For now, I'm running tests via ssh session on container (while viewing emulator via vnc -- which is nice).

Next step is to experiment with emulator snapshots (probably a better fit for travis as opposed to docker checkpoints). See how it improves boot speed.

Then experiment with methods to deliver snapshot to travis.

Another longer term option is to rent a hardware accelerated VM and experiment with ways to set-up emulators and make available for testing, etc..

I hope to be able to set-up an experimental project on travis and be able to ask some follow-up questions shortly.

Thanks for all the great feedback!

**Comment by thyrlian** [comment]
Good to hear your feedback.

What kind of adb port forwarding issue you're suffering from?  Maybe this one:
> When you have `adb` available also on your host machine.  Make sure that your adb client (from the host machine) talks to the adb server inside the container, instead of the local one on the host machine. This can be achieved by running adb kill-server (to kill the local server if it's already up) before firing adb connect command above.

Good luck and have fun!

**Comment by mmcc007** [comment]
On remote linux VM, have no problem connecting to emulator in container from host using adb.
Somehow adb on host finds emulator in container without needing 'adb connect'.

The problem seems to be with the command which flutter tooling issues:
```
sdk/platform-tools/adb -s emulator-5556 forward tcp:0 tcp:57719
40322
```
Port 57719 is opened by flutter app on emulator in container (it is obtained by flutter tooling via adb from the app log during app startup ), port 40322 is expected to be available on host).
These port numbers change on each run.
 
Anyway, I suspect port 40322 is being forwarded (in container). This port is not being exposed by container to the host (afaik). 

BTW: when I try the suggestion I can no longer connect:
```
$ sdk/platform-tools/adb devices -l
List of devices attached
emulator-5556          device product:sdk_phone_armv7 model:sdk_phone_armv7 device:generic transport_id:2
$ sdk/platform-tools/adb kill-server
$ sdk/platform-tools/adb devices -l
$ sdk/platform-tools/adb connect 127.0.0.1:5037
error: protocol fault (couldn't read status): Connection reset by peer
$ sdk/platform-tools/adb devices -l
List of devices attached
error: protocol fault (couldn't read status): Connection reset by peer
```
But, as mentioned, I don't need to fix this for now since I am running an ssh session in container.

**Comment by thyrlian** [comment]
Good to know the trick played by flutter, thanks.

**Comment by mmcc007** [comment]
Good news!

An emulator, restarted in a remote linux VM, with a default snapshot, start's up in about 40 seconds compared to like 4-5 minutes on travis. So I built a docker image from your vnc image with the default emulator snapshot and was able to run a flutter test using the new docker image.

So, the next step is to publish the new docker image, called 'hot-emulator', and then load it up in travis and see how fast the flutter test runs. 

I'm still stuck with the port forwarding problem, described in earlier comment, when running a flutter test. So, there are 2 approaches:
1. try to resolve how to expose an arbitrary port from a container to a host at runtime.
1. try to mount the repo containing the flutter project (at the root of repo), and the flutter installation,  as a volume and run the flutter test in the container via ssh (I've tested this using the /sdk mount and it works. Adding the repo to the container as a separate volume is better for flutter projects.. otherwise have to move repo and flutter installation to the /sdk mount point).

Any tips on 1. or 2. would be helpful. Don't know much about option 1. But 2. hopefully will work.

Will post experiment to github as demo and for any feedback, etc...

**Comment by thyrlian** [comment]
Good job.

I think to build an experimental image based on the vnc image is OK, but later it's better to build based on the non-vnc image, as it's smaller, and you don't really need vnc when running on TravisCI.

WRT #2, usually there are 3 approaches to load the project source code:
* Add the source code to the image, and version it, but you'll need to build / publish a new image every time.
* mount the source code volume to the container (as you mentioned).
* use git (included in the image) to clone the code (your project code is open sourced, which should be fine).

**Comment by thyrlian** [comment]
WRT the point 1, sorry about my poor knowledge of flutter.  But according to what you've described, it's all about the dynamic port, it's changing each time.

Instead of using any service discovery tool, what come to my mind is that you could try:
* Make a daemon script (and control it by [supervisord](https://github.com/thyrlian/AndroidSDK/blob/master/android-sdk/supervisord.conf)), monitoring the adb port in use;
* Write the detected new port number to a file, then access the file from outside (since the file name is always the same).
* Or build a one-liner lightweight web service, and return the port number, something like [this](https://github.com/thyrlian/SonarOnDocker#pitfalls):
> **Web Server**: Yet another hack - what if we set up a minimal (one-liner) web server in the MySQL container that responds with the database status?  Something like `while true; do echo -e "HTTP/1.1 200 OK\r\n\r\n$(db_status)" | nc -l -q 0 -p 9999; done`.

**Comment by mmcc007** [comment]
BTW: I posted some source code for the hot emulator docker image:
https://github.com/mmcc007/hot-emulator
and am setting-up a demo of the experiment to run a flutter test:
https://github.com/mmcc007/hot-emulator-demo
To get flutter test to run, will probably, for now, move the app and flutter install to /sdk and run from ssh. Hopefully all this will result in a faster-running test... 🤞

Can then look at improving by using your suggestions above, etc...

**Comment by mmcc007** [comment]
Just got it working:
https://travis-ci.com/mmcc007/hot-emulator-demo/builds/105571822

Not as fast as I hoped. But still pretty good. Not sure how I can best improve it. Maybe adding gradle caching?

If you have any suggestions for optimizing, it would be great to get your feedback

Thnx for such a great tool.

**Comment by thyrlian** [comment]
@mmcc007  good job 👍

Yes, especially when your project is big and complicated, adding gradle cache would definitely help.  I know it works for CircleCI, but never tried with Travis CI.

Thanks for the compliment 😀
