### ISSUE TITLE
Docker images prior to v3 do not contain android 28 sdk

### ISSUE THREAD

**Issue by rossmckelvie** [thyrlian/AndroidSDK#20]
I fixed the Android 28 issue in PR #17. We have been using the latest image but with the v3 upgrade we locked down to the previous version on docker hub, 2.5. Unfortunately our builds fail due to not having android-28 fix, there aren't any tags that contain this working version, unless we also are prepared for the upgraded ubuntu & gradle environment.

Would it be possible to push a 2.6 tag to one of the older build hashes that contains the android 28 fixes prior to v3?

**Comment by thyrlian** [comment]
Just try to understand the question:

**Comment by thyrlian** [comment]
Sorry for any inconvenience.

Just try to understand the problem:

You want a v2.6 on Docker Hub, the same content as [v2.5](https://github.com/thyrlian/AndroidSDK/blob/master/CHANGELOG.md#25), plus your previous fix for Android 28 license?

Before working on and pushing the v2.6, I'd like to ask a few questions:

* Does the new Ubuntu OS bring any problem to you, which stops you from using v3.0?
* Do you use the image's built-in gradle instead of the `gradlew` from your project?  The built-in gradle is only for some demo / trial purpose.  Actually, I'm thinking about dropping gradle and kotlinc from this Docker image.

Thanks.

**Comment by rossmckelvie** [comment]
I did not have the time to evaluate the breaking changes of a major version bump, and was disappointed to see the working version I assisted with to not be found anywhere in the v2 images.

**Comment by rossmckelvie** [comment]
Looking at the commit log I saw “update Dockerfile” multiple times. After reviewing the changes it’s a different image, but the combination of losing a stable v2 tag for Android-28 and indescriptive commit messages, I just rolled back our mirror of the image and my improvements since we build off of your dockerhub repo

**Comment by thyrlian** [comment]
Pushed.

Please check the [changelog](https://github.com/thyrlian/AndroidSDK/blob/master/CHANGELOG.md#26) and grab the `2.6` image from Docker Hub.

**Comment by rossmckelvie** [comment]
Thank you so much @thyrlian !

**Comment by thyrlian** [comment]
My pleasure @rossmckelvie, enjoy :)
