### ISSUE TITLE
Default locale charmap is ANSI_X3.4-1968 instead of UTF-8

### ISSUE THREAD

**Issue by antygravity** [thyrlian/AndroidSDK#21]
I got problem when run unit test. When run test which uses not ANSI characters it fails.
When I check charmap:
`locale charmap` it returns 
    ANSI_X3.4-1968
So is it possible to change default charmap to UTF-8?
I fixed this in container using commands:
`apt install locales
    locale-gen en en_US en_US.UTF-8
    update-locale en_US.UTF-8
    export LC_ALL=en_US.UTF-8`. 
But this can be done in more proper way.

**Comment by antygravity** [comment]
My fix:removed step `apt-get remove -y locales`
and added
`ENV LC_ALL en_US.UTF-8`
https://github.com/antygravity/AndroidSDK/blob/master/android-sdk/Dockerfile

**Comment by thyrlian** [comment]
Hi @antygravity, thanks for reporting the issue and providing a solution for it.

Please find below some comments from my side, glad to discuss with you.

* the `locales` package is only needed during `openssh-server` installation and configuration, that's why it's removed afterwards.  And I believe most of the time, `locales` is not required for running Android unit test.

* I've encountered similar issue previously, please take a look at the slide [here](https://speakerdeck.com/thyrlian/android-meets-docker-5?slide=26).  For some encoding problem, it's better to fix on the file's side rather than the environment, as the test should be machine-independent.

* If by any chance, we have to configure the environment.  I would suggest putting the configuration code into your build script, so that it could be run successfully everywhere.  Let's say on your colleague's local machine, even without running in any docker container, it should work.  As well as later if you decide to move to another CI provider, or not using this Docker image any more.  You could still call your build script to have the configuration being effective.

What do you think?

And it would be great if you could post some unit test code which caused this problem.  And we could try to reproduce it and find a solution together.

Thanks :)
