### ISSUE TITLE
Adding the NDK

### ISSUE THREAD

**Issue by fluffrabbit** [thyrlian/AndroidSDK#22]
I was concerned about how the Android SDK EULA system would ruin reproducibility, but I saw that you have [a solution for that](https://github.com/thyrlian/AndroidSDK/blob/master/android-sdk/license_accepter.sh), so I'm wondering a couple of things:

* Can you do a version with the NDK? It's in common use and it would save people from logging into their dockers to install it themselves.
* Can I do a version with the NDK? I'm wondering about those hexadecimal codes. Looks like black magic to me. I don't have to actually use sdkmanager do I? Or is that all done from the command line within the docker? Yeah I'm new...

Many thanks.

**Comment by thyrlian** [comment]
Hi @fluffrabbit, thanks for your feedback.  I agree that NDK is necessary, some users would need it.

I actually have both **NDK** and **NDK (Side by side)** installed on my local machine, but can't see any NDK specific license under the directory `$ANDROID_HOME/licenses`.

<img width="208" alt="licenses" src="https://user-images.githubusercontent.com/352956/63255558-47520d80-c276-11e9-9fb8-0f8fe3331818.png">

The [script solution](https://github.com/thyrlian/AndroidSDK/blob/master/android-sdk/license_accepter.sh) you've found is the correct one, which merely creates an empty license file and writes hexadecimal data to it.  It doesn't accept the license by using sdkmanager.

Please, once you find any license doesn't appear there, please help add it to the script and create a PR for it.  Thanks in advance.

**Comment by fluffrabbit** [comment]
So in other words, you don't need to add any NDK license hexadecimal to the script for it to work? That's great!

My concern with packaging things this way is deterministic builds. Since you've set it up to not require any manual intervention, is there a best practice to get the NDK in the thing following a `docker pull thyrlian/android-sdk`?

Sorry, I'm new to Docker and I'm not so articulate when discussing Android weirdness.

**Comment by thyrlian** [comment]
So far you don't need to do anything, as all known licenses have already been added to the script.

Regarding how exactly does it work:

* The Docker image itself doesn't contain NDK (and we should not do so), it only has the barebone Android SDK downloaded from the official website (and in the future will be removed, due to the terms and agreement).
* The Docker image should not contain any specific Android SDK package.  Why?  Different developer / app has different need, the dependent package(s) should be downloaded later by developer themselves, not prior in image building phase.  Plus, if we drop everything inside, the image will be too big.  And Android SDK packages get update quite frequently, we should not spend the time on maintaining the Docker image.
* So how should we get specific package to work with this Docker image?  Just forget about the Docker image (just treat it as a class in OO terminology), it's more like a blueprint.  When you create a Docker container (treat it as an instance in OO terminology), you should mount a volume (a persistent storage), and there you persist all downloaded / upgraded Android SDK package(s).  Thus, the SDK is decoupled from the Docker image, and is persisted, maintained over a sharable disk volume.

Hope it's clear for you.

**Comment by fluffrabbit** [comment]
If I have to do it that way, I'm going to drop the Android platform into the garbage.

* The Android Open Source Project is made available under FLOSS licenses, therefore any binaries derived from that libre source code are not subject to EULAs, T&C, etc. The "licenses" are a lie. At least in the US.
* I'm not suggesting changing this package, I'm suggesting forking it into a version that includes the NDK as a first-class Android build tool.
* OO stuff still requires downloading from the Internet. We need an offline disk image that always contains the same code so as to emulate the GCC desktop build experience.

I hope I have conveyed the thrust of it.

**Comment by thyrlian** [comment]
Regarding the license, I can't tell too much.  And you're right, there is already a debate here:
https://www.zdnet.com/article/no-google-is-not-making-the-android-sdk-proprietary-whats-the-fuss-about/

Any package is independent from this Docker image, including NDK.  So yes, once you have the package, it's ready to use.  Thus I would say it's already the first-class citizen :)

I'm not sure if I understand your 3rd bullet point correctly, but do you mean to keep the build cache?

Thanks.

**Comment by fluffrabbit** [comment]
I'm not sure about tthat debate. A lot of folks in the comment thread were on the wrong side of it, though I didn't get to read through the discussion completely as the ads crashed my browser. :/

I'm glad we're on the same page regarding the liberty of the SDK anyways.

One of my points is that it's important to boycott frivolous updates to development platforms. A developer has to build against a specific API version, and if an app takes 10 years to become stable and the dev can't afford to spend time updating anything, it had better build the same way 10 years later. GCC really shines because we can all still build in C89 mode; in fact that is a best practice.

When you don't keep the entire build environment in one place, shit can happen to it. Relying on users to download shit into volumes is not a good idea. You know how an ISO works? You boot it, it's the same data, it works the same way, and it never changes.

I understand that deterministic builds can be performed through careful configuration of Gradle, but it is inconvenient to set such a system up initially, and the various deterministic aspects of it can vary from version to version, with different versions of Gradle, different versions of Java, and other complexities that scare would-be mobile developers away. Mind you, we do not have these complexities when targeting HTML5 (nor on desktop obviously).

If you ask me, the best solution is for this docker to reference a specific version of each component and include full working copies of those versions of those components in its filesystem. The versions can be updated with new versions of the docker, but each docker version tag should refer to the version that has version X of Android tool A, version Y of Android tool B, and version Z of Android tool C, with additional different versions available to install at the user's discretion.

The experience for the user of this docker would be:

```
# From the shell
docker pull thyrlian/android-sdk

# Makefile
DROID_PREFIX=sudo docker run --rm -v $(shell pwd):/src thyrlian/android-sdk
online:
	$(DROID_PREFIX) /bin/bash -c "cd /src/android; gradle build"

offline:
	$(DROID_PREFIX) /bin/bash -c "cd /src/android; gradle build --offline"
```

And the NDK should be in there somewhere, either coming by default or configured in the makefile.

**Comment by thyrlian** [comment]
I got your point.

Should the Docker image contains the entire build environment?  Yes, it should - for people to have consistent context which should in theory lead to reproducible results.  Meanwhile, a fragmented build environment would cost extra configuration and effort, nobody would prefer that.

Then why doesn't this Docker image container any SDK component?  As mentioned earlier:
* To keep the size in shape.  Downloading is an expensive activity.
* Avoid various Docker images fragmentation.  Because there are a bunch of different API levels, and even endless combination of API levels * some other packages / dependencies.  However, this doesn't stop user to build a custom image on his / her own - by inheriting this image and add new packages on top of it.

Yes, you said about different tags for different versions of tools.  Ideally this is doable by using `ARG`, so that you can pass different versions at the image build time to build custom image.

Another issue mentioned by you - how to keep the build environment a strong reliable constant environment?  You have given the case of ISO.  In fact, external volume could still achieve that.  Just like building an image.  We just need to carefully prepare the external volume at the first time, install only the necessary SDK packages, into the external volume (with your powerful admin access permission).  Later on, on Docker side, just mount it as read-only, that's it.  Of course, if you still want to access the external volume out of Docker usage context, you can simply use non-admin account which has read-only permission to access it.  In this case, everything is read-only, there will be no surprising unexpected update / change of SDK packages.

**Comment by fluffrabbit** [comment]
Builds should be deterministic for remote users over the Internet. Simplying installing the docker and running the Makefile should be enough to get bit-for-bit symmetry with all of the dependencies. This shouldn't be theoretical, this should be in practice.
