### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by eliaweiss** [thyrlian/AndroidSDK#31]
I follow the instruction, but this cmd failed:

docker run -it --rm -v $(pwd)/sdk:/sdk thyrlian/android-sdk bash -c 'cp -a $ANDROID_HOME/. /sdk'

error:

docker: Error response from daemon: create $(pwd)/sdk: "$(pwd)/sdk" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.

**Comment by eliaweiss** [comment]
this works for me on win

docker run -it --rm -v "%cd%"/android-sdk:/sdk thyrlian/android-sdk bash -c "cp -a $ANDROID_HOME/. /sdk"

**Comment by thyrlian** [comment]
Hi @eliaweiss, thanks for reporting the issue and offering the solution.

Sorry for my bad, I should have also mentioned the corresponding command for Windows.

And you're right.  On Windows, user just need to change `$(pwd)` to `%cd%` for current directory.

BTW, I've changed this issue's title, so that it will be easier for others to find it later.

Thanks.
