### ISSUE TITLE
Warning: Failed to read or create install properties file. 

### ISSUE THREAD

**Issue by 72L** [thyrlian/AndroidSDK#34]
Following the instructions for Emulator, I get an error:

```
root@768cc52f988b:~# sdkmanager "platform-tools" "platforms;android-24" "emulator"
Warning: Failed to read or create install properties file.                      
root@768cc52f988b:~#                    ] 10% Installing Android SDK Platform 24
```

**Comment by 72L** [comment]
fixed this by removing the `:ro` from this line in the SSH instructions:
```
docker run -d -p 2222:22 -v $(pwd)/sdk:/opt/android-sdk:ro android-sdk
```

**Comment by thyrlian** [comment]
There are various ways of managing SDK.  Personally speaking, I would not recommend dropping a whole package of SDK into a container.  Three reasons:
* It would lead to a massive image.
* The image needs to be updated frequently.
* Re-distribute SDK violates its license.

That's why I decoupled SDK from the image.  You can mount it from any NFS, or host it on Amazon S3.  Please read the README carefully - `ro` here is to avoid accidental updating/modification of SDK in parallel from different instances.  But if you're sure there will be only one instance at a time, or no parallel updating, that's totally fine to remove `ro`.

Have fun :)
