### ISSUE TITLE
Q: Please help starting the emulator

### ISSUE THREAD

**Issue by aokhrimenko** [thyrlian/AndroidSDK#45]
Hi!

I'm playing with emulator. The goal is to run the emulator and connect to it via VNC.
I've done with the following steps, succeeded to connect to VNC, but saw only a blank rectangle instead of amulator window.
Help me please :)

I've tried these steps on both Docker for Mac and on Cloud computing services pod on Hetzner (Ubuntu 20.04, AMD EPYC 2nd Gen processor). In both cases I've got the same black rectangle. 

Here are the steps I've done:
Host
	⁃	docker run -it --rm -v $(pwd)/sdk:/sdk thyrlian/android-sdk bash -c 'cp -a $ANDROID_SDK_ROOT/. /sdk'
	⁃	docker run -d -p 5901:5901 --name emulator -v $(pwd)/sdk:/opt/android-sdk thyrlian/android-sdk-vnc
	⁃	docker exec -it emulator bash

Container
	⁃	sdkmanager "platform-tools" "platforms;android-25" "emulator"
	⁃	sdkmanager "system-images;android-25;google_apis;armeabi-v7a"
	⁃	echo "no" | avdmanager create avd -n test -k "system-images;android-25;google_apis;armeabi-v7a"
	⁃	emulator -avd test -noaudio -no-boot-anim -gpu off

Output of the `emulator`:
```
emulator: WARNING: encryption is off
emulator: INFO: QtLogger.cpp:68: Warning: XKeyboard extension not present on the X server ((null):0, (null))


NativeEventFilter: warning: cannot get mod mask info
WARNING. Using fallback path for the emulator registration directory.
Your emulator is out of date, please update by launching Android Studio:
 - Start Android Studio
 - Select menu "Tools > Android > SDK Manager"
 - Click "SDK Tools" tab
 - Check "Android Emulator" checkbox
 - Click "OK"

emulator: ERROR: AdbHostServer.cpp:102: Unable to connect to adb daemon on port: 5037
emulator: emulator window was out of view and was recentered
```

Then on host (Mac) I've connected to VNC server via Screen Sharing.
<img width="1022" alt="Знімок екрана 2020-11-13 о 19 03 12" src="https://user-images.githubusercontent.com/6370006/99105384-1b454980-25eb-11eb-8539-c099dc1b80dc.png">
<img width="1020" alt="Знімок екрана 2020-11-13 о 19 03 43" src="https://user-images.githubusercontent.com/6370006/99105397-1f716700-25eb-11eb-88eb-37473faabc68.png">

**Comment by thyrlian** [comment]
Hi.

First of all, congratulations on your successful start of the container, everything you did about that is correct.

Regarding the black screen:
* You've installed all correct dependencies: `"platform-tools" "platforms;android-25" "emulator"`, as well as the emulator system image
* The Docker image itself already has proper environment variables (for emulators) set (so you don't have to)
* Most of the output you've got are warnings, feel safe to ignore
* I've noticed that you launched emulator with `-gpu off`, try a different option to enable proper rendering: `emulator -avd test -no-audio -no-boot-anim -accel on -gpu swiftshader_indirect &`
* There is an error message: `emulator: ERROR: AdbHostServer.cpp:102: Unable to connect to adb daemon on port: 5037`, please try to restart the adb server inside the container.  After that, try run `adb devices` a couple of times to see what information it gives
* The black screen sometimes is not really a problem, but requires patience, you just have to wait for the Android system to become ready.  Because it's emulation in a container, for sure it will be slow.

Hope you'll get it work soon.

**Comment by aokhrimenko** [comment]
Thank you very much! Enabling GPU and patience helped 👍

**Comment by thyrlian** [comment]
So it's working for you now? @aokhrimenko

**Comment by thyrlian** [comment]
Probably you're patient, but the CI machine won't be like you.  Thus I suggest you check the new release 6.0, with the support of [Firebase Test Lab](https://github.com/thyrlian/AndroidSDK#firebase-test-lab), to run your UI tests fast and stable.

**Comment by aokhrimenko** [comment]
@thyrlian thanks a lot. Yes, it's working, but verrrrrry slowly. Thanks for advice - will have a look ;)
Good luck, mate!
