### ISSUE TITLE
Illegal redistribution of Android SDK

### ISSUE THREAD

**Issue by Malinskiy** [thyrlian/AndroidSDK#47]
Hi,

Just an FYI it is illegal to create public docker images containing the Android SDK as per [response from Google](https://issuetracker.google.com/issues/73287051#comment6).

Cheers

**Comment by thyrlian** [comment]
Hi @Malinskiy,

First of all, thank you for the heads-up :)

In fact, this is not a problem for this implementation:

* The legal concern has been already considered from the beginning of this repo:

  > not to redistribute the SDK is the legal behavior.
* According to the [philosophy](https://github.com/thyrlian/AndroidSDK#philosophy), Android SDK shouldn't be part of the image, for several reasons:

  * > You can maintain an external persistent SDK directory, and mount it to any container.
  * > Instead of one dedicated Docker image per Android API level (which will end up with a ton of images), you just have to deal with one image.

The current `Dockerfile` is not tied to the Android SDK, except for the `PATH` environment variable, which is not a big deal.

Thanks again for your concern.

From the next major release on, we're going to remove Android SDK completely, as well as Gradle and Kotlin.
