### ISSUE TITLE
The Android X framework has compatibility issues

### ISSUE THREAD

**Issue by DreamPWJ** [thyrlian/AndroidSDK#51]
android:text="@{`$` Packaging appears to become. ???? Abnormal display

**Comment by DreamPWJ** [comment]
![image](https://user-images.githubusercontent.com/16730031/102965154-3da27f00-4528-11eb-9332-bc27fd2da622.png)

**Comment by thyrlian** [comment]
Hi, I've tested strings like `¥Ұ` in a demo project inside the Docker container (`thyrlian/android-sdk:6.0`), it has no problem at all, `./gradlew build` command was executed without any error => `BUILD SUCCESSFUL`.

**Comment by thyrlian** [comment]
This is an open-source project, I'm not paid for working on it.  Every minute I spend on it should be respected and valued.

Thus, a clear description of the problem and precise steps to reproduce the bug are preferred.

For your case:

* The title says "_**The Android X framework has compatibility issues**_"
  * This Docker image provides merely an environment, it doesn't even come with AndroidX.  Why do you think it's related?
  * From your description below the title, I can't find any feature that is from AndroidX or any clue that is telling the issue was caused by AndroidX library.  You should **narrow down** the problem.
* The description says "**_android:text="@{$ Packaging appears to become. ???? Abnormal display_**"
  * You didn't even provide me the problematic string `¥Ұ`, which is required for debugging.  Luckily I'm Chinese, I know where to get it.
  * What does "**_Abnormal display_**" mean?  Abnormal during gradle build (display junk character in build logs)?  Or when running on a device (if so, what kind of device is that?)
  * Nobody is yourself.  When reporting an issue, you should provide as detailed information as possible.  For example, what gradle build command have you executed?  Or what else build or run steps I should try?  Without those info, I would have to try all possibilities, which are time-consuming.
* The buggy line shows the use of `@{}` syntax for layout expression.  To isolate the problem, you should try two things:
  * Hardcode the "abnormal" string `¥Ұ` into a text field without using layout expression, to see if it's working or not;
  * Use the layout expression together with other ASCII characters instead of Unicode characters, to see if it's working or not.

With the above procedure, I'm pretty sure that your bug report would be more precise and easy to follow.  Or probably you would even have the problem solved by yourself already.

After reading it again carefully, I believe the root cause is from your **encoding**:
You are using the fullwidth form of the single quote instead of the halfwidth form of the single quote.

Last but not least, the lesson I've learned is that I should create a bug reporting guideline (template), not simply assuming everyone thinks thoroughly and provides a precise bug report.
