### ISSUE TITLE
'WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

### ISSUE THREAD

**Issue by Marietto2008** [thyrlian/AndroidSDK#57]
Hello.

what it means "Solves the problem of "It works on my machine, but not on XXX machine" ? I intended that your image works on every machine,from windows,to mac to arm32 or 64. It's not like this,the title is misleading. I tried to run your image on the jetson nano and I've got this error :

root@zi-desktop:~/Desktop/zi/Work/I9/Android# docker run -it --rm -v $(pwd)/sdk:/sdk thyrlian/android-sdk bash -c 'cp -a $ANDROID_SDK_ROOT/. /sdk

'WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

standard_init_linux.go:219: exec user process caused: no such file or directory

**Comment by thyrlian** [comment]
Thank you for your interest.

First of all, it's not a bug.  You probably misunderstood the concept of "_It works on my machine_", it's not about **cross-platform**, but it aims for **consistency**.  An introduction about that can be found [here](https://hackernoon.com/but-it-works-on-my-machine-74b6875ab4e7).

Even for the cross-platform software, they often cover only the most popular platforms.  We should not split hairs, otherwise, the argument will never end: adding support for various OS: Solaris, FreeBSD?  Or adding support for other architectures: MIPS, RISC-V?  That's not the goal.

The purpose of this Docker image is to help engineering teams increase productivity.  Running on an ARM-based Jetson Nano won't achieve such an objective.  However, I don't wanna show any bias here, I would say deploying to Jetson Nano totally makes sense for personal projects or just for fun.  Furthermore, it should be feasible as well, as the base image [Ubuntu](https://hub.docker.com/_/ubuntu?tab=tags) supports multi-arch, including ARMv7.  Why don't you create a PR for that (you can refer to this article: [Multi-arch build and images, the simple way](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/).  Please make sure that the image is properly tested)?  Any contribution is welcome.

**Comment by yaizudamashii** [comment]
While I was able to build an arm64 docker image making a few modifications, I don't know how meaningful that is, since sdkmanager's "emulator" package doesn't seem to be available for arm64.    Does anyone know if that is available anywhere?  

For those who are curious, you can see the modifications I made in this branch
https://github.com/yaizudamashii/AndroidSDK/tree/arm64-builds

**Comment by leonitousconforti** [comment]
Thank you @yaizudamashii for providing your branch, I was able to build the docker image from your branch just fine. After building the docker image, I installed a couple of things using the sdk manager following the readme:

```
sdk/cmdline-tools/tools/bin/sdkmanager "platform-tools" "platforms;android-31" "emulator" "system-images;android-31;default;arm64-v8a"
```

I then made a new avd by running
```
docker run -it -v $(pwd)/sdk:/opt/android-sdk:ro android-sdk /bin/bash

avdmanager create avd -n test -k "system-images;android-31;default;arm64-v8a"
```

Finally, I tried to start the emulator from the docker container
```
emulator -avd test -no-audio -no-boot-anim -no-window -accel on -gpu off &
```

which fails with the error `bash: /opt/android-sdk/emulator/emulator: cannot execute binary file: Exec format error`
I tried running executing `/opt/android-sdk/emulator/emulator` and got the same result.

What is interesting to me is that if I open a new terminal on my host machine, and navigate to the directory where the sdk is (not the sdk installed on my system, the one mounted for the android-sdk container) and then execute `./sdk/emulator/emulator` the binary runs just fine

Is this a docker issue?? The binary will run just fine on my host machine (m1 macbook air) but won't run when mounted inside a docker container?? The only thing I could think of is that this is an issue with the base ubuntu:20.04 image but it is supposed to support multi-arch

**Comment by yaizudamashii** [comment]
Hi @leonitousconforti I believe there is no emulator for arm64 Linux provided by Google.  Google does provide arm64 mac emulator so that's why the sdk works on your host computer.  So sadly arm64 image of this repo isn't useful until Google provides linux arm64 emulator.  Once we get it, we can merge the branch into this repo.

**Comment by leonitousconforti** [comment]
@yaizudamashii see https://github.com/yaizudamashii/AndroidSDK/pull/1

**Comment by thyrlian** [comment]
+1 for @yaizudamashii, not only the `emulator` binary but also other binaries under the `bin` directory, they are not compiled for arm64 Linux.  Previously, in the older release of Android SDK, if I'm not mistaken, some binaries even had different variations - for different architectures.

But it's great that @leonitousconforti you made it work by compiling it yourself from the Android source repository and adding the missing dependencies.  Really appreciate your awesome work, looking forward to the further news.

Just out of curiosity, why are you guys so keen to run the Android SDK on ARM machines (except for the powerful Apple ARM machines)? :)

**Comment by yaizudamashii** [comment]
@leonitousconforti Thank you for all your work, will test it this weekend to see if I will get the the place you got to.
@thyrlian For me because bare metal on AWS is super super expensive while ARM Ubuntu is cheap...

**Comment by yaizudamashii** [comment]
A minor followup, I am now running the images on GCP instances, from which you can (relatively) cheaply use nested virtualization.  This documented provided by google helped a lot, 

https://source.android.com/devices/automotive/start/avd/cloud_emulator

the only differences being 1. use ubuntu-22 based images instead of ubunt-18 based images as instructed (section **Create a Linux VM in GCE**: 2), and using this repo's image (in my opinion far superior than the one Google provides) instead of Google's container (section **Start the hosted containers**: 1)

The cost comes out to ~$140 a month, much cheaper than AWS bare metal.
